#!/bin/sh
# This is a generated file; do not edit or check into version control.
export "FLUTTER_ROOT=/Users/zhaopeng/Desktop/Hidoo/decode/decode/flutter/flutter"
export "FLUTTER_APPLICATION_PATH=/Users/zhaopeng/Desktop/nova/decode/flutter/test/learn/hello_world"
export "FLUTTER_TARGET=/Users/zhaopeng/Desktop/nova/decode/flutter/test/learn/hello_world/lib/main.dart"
export "FLUTTER_BUILD_DIR=build"
export "SYMROOT=${SOURCE_ROOT}/../build/ios"
export "OTHER_LDFLAGS=$(inherited) -framework Flutter"
export "FLUTTER_FRAMEWORK_DIR=/Users/zhaopeng/Desktop/Hidoo/decode/decode/flutter/flutter/bin/cache/artifacts/engine/ios"
export "FLUTTER_BUILD_NAME=1.0.0"
export "FLUTTER_BUILD_NUMBER=1"
export "DART_OBFUSCATION=false"
export "TRACK_WIDGET_CREATION=true"
export "TREE_SHAKE_ICONS=false"
export "PACKAGE_CONFIG=.packages"
